#!/usr/bin/env python3
"""Generate narrative simulation GIF showing training vs test occlusion types.

Two rows tell the story:
  Row 1 (Training): clean success | fingerprint 90% failure
  Row 2 (Testing):  light rain success | heavy rain failure

Rain frames are generated by applying the Rain model to clean simulation frames.
"""

import subprocess
import sys
import tempfile
from pathlib import Path

import numpy as np

# Add camera_occlusion to path
sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "camera_occlusion"))

from PIL import Image, ImageDraw, ImageFont
from camera_occlusion.camera_noise import Rain

ROOT = Path(__file__).resolve().parent.parent
RESULTS = ROOT / "results"
OUT = ROOT / "docs" / "figures"


def get_font(size=15):
    for font_path in [
        "/System/Library/Fonts/Supplemental/Arial Bold.ttf",
        "/System/Library/Fonts/Supplemental/Helvetica Bold.ttf",
        "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf",
    ]:
        try:
            return ImageFont.truetype(font_path, size)
        except (OSError, IOError):
            continue
    return ImageFont.load_default()


def extract_frames(video_path, fps=8):
    """Extract frames from mp4 as list of numpy arrays (HWC uint8)."""
    with tempfile.TemporaryDirectory() as tmpdir:
        cmd = [
            "ffmpeg", "-y", "-i", str(video_path),
            "-vf", f"fps={fps}",
            f"{tmpdir}/frame_%04d.png",
        ]
        subprocess.run(cmd, capture_output=True, check=True)
        frames = []
        for p in sorted(Path(tmpdir).glob("frame_*.png")):
            frames.append(np.array(Image.open(p).convert("RGB")))
    return frames


def apply_rain(frames, num_drops, radius_range):
    """Apply rain effect to a list of frames. Each frame gets fresh drops."""
    out = []
    for f in frames:
        rain = Rain(num_drops=num_drops, radius_range=radius_range)
        out.append(rain.apply(f.copy()))
    return out


def make_panel(img_np, crop_top=30, size=(280, 224)):
    """Crop baked-in label, resize."""
    h, w = img_np.shape[:2]
    cropped = img_np[crop_top:h, :, :]
    pil = Image.fromarray(cropped).resize(size, Image.LANCZOS)
    return pil


def add_label(img, text, color, position="bottom", bar_height=26):
    """Add a colored label bar to a PIL Image."""
    w, h = img.size
    font = get_font(14)

    draw = ImageDraw.Draw(img)
    if position == "bottom":
        y0 = h - bar_height
        draw.rectangle([(0, y0), (w, h)], fill=color)
        bbox = draw.textbbox((0, 0), text, font=font)
        tw = bbox[2] - bbox[0]
        tx = (w - tw) // 2
        draw.text((tx, y0 + 5), text, fill="white", font=font)
    return img


def add_section_header(width, text, bg_color, height=28):
    """Create a section header bar."""
    header = Image.new("RGB", (width, height), bg_color)
    draw = ImageDraw.Draw(header)
    font = get_font(16)
    bbox = draw.textbbox((0, 0), text, font=font)
    tw = bbox[2] - bbox[0]
    tx = (width - tw) // 2
    draw.text((tx, 5), text, fill="white", font=font)
    return header


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    output = OUT / "simulation_demo.gif"

    pw, ph = 240, 192  # panel dimensions
    gap = 2            # gap between panels
    bar_h = 26         # label bar height
    header_h = 26      # section header height

    # --- Load source videos ---
    print("Extracting frames...", flush=True)
    clean_frames = extract_frames(
        RESULTS / "coke_can_fingerprint" / "animations" / "clean.mp4", fps=4)
    fp_frames = extract_frames(
        RESULTS / "coke_can_fingerprint" / "animations" /
        "worst_fingerprint_budget_0.90.mp4", fps=4)

    # Generate rain frames from clean video
    print("Applying rain to clean frames...", flush=True)
    rain_light = apply_rain(clean_frames, num_drops=60, radius_range=(3, 12))
    rain_heavy = apply_rain(clean_frames, num_drops=500, radius_range=(8, 35))

    n = min(len(clean_frames), len(fp_frames))
    print(f"  {n} frames per panel", flush=True)

    # --- Layout ---
    # Row 1: [header] [clean success] [fingerprint failure]
    # Row 2: [header] [rain light success] [rain heavy failure]
    row_w = pw * 2 + gap
    row_h = ph  # panel with labels drawn inside

    combined_frames = []
    for i in range(n):
        # Top row: training data
        p_clean = make_panel(clean_frames[i], size=(pw, ph))
        add_label(p_clean, "Clean - Success", "#1b7a30")

        p_fp = make_panel(fp_frames[i], size=(pw, ph))
        add_label(p_fp, "Fingerprint 90% - Failure", "#c62828")

        top_header = add_section_header(
            row_w, "TRAINING DATA: Fingerprint & Glare", "#2c3e50")
        top_row = Image.new("RGB", (row_w, ph), "black")
        top_row.paste(p_clean, (0, 0))
        top_row.paste(p_fp, (pw + gap, 0))

        # Bottom row: test data (rain, never seen)
        p_rain_light = make_panel(rain_light[i], crop_top=30, size=(pw, ph))
        add_label(p_rain_light, "Rain 10% - Success", "#1b7a30")

        p_rain_heavy = make_panel(rain_heavy[i], crop_top=30, size=(pw, ph))
        add_label(p_rain_heavy, "Rain 90% - Failure", "#c62828")

        bot_header = add_section_header(
            row_w, "TEST DATA: Rain (Never Seen in Training)", "#1a237e")
        bot_row = Image.new("RGB", (row_w, ph), "black")
        bot_row.paste(p_rain_light, (0, 0))
        bot_row.paste(p_rain_heavy, (pw + gap, 0))

        # Stack vertically: top_header | top_row | gap | bot_header | bot_row
        total_h = header_h + ph + 3 + header_h + ph
        frame = Image.new("RGB", (row_w, total_h), "#1a1a2e")
        y = 0
        frame.paste(top_header, (0, y)); y += header_h
        frame.paste(top_row, (0, y)); y += ph + 3
        frame.paste(bot_header, (0, y)); y += header_h
        frame.paste(bot_row, (0, y))

        combined_frames.append(frame)

    # Quantize and save
    print("Saving GIF...", flush=True)
    quantized = [f.quantize(colors=96, method=Image.Quantize.MEDIANCUT)
                 for f in combined_frames]

    quantized[0].save(
        output,
        save_all=True,
        append_images=quantized[1:],
        duration=250,  # 4 fps
        loop=0,
    )

    size_kb = output.stat().st_size / 1024
    print(f"  -> {output} ({size_kb:.0f} KB)", flush=True)


if __name__ == "__main__":
    main()
