#!/usr/bin/env python3
"""Generate narrative simulation GIF: training corruptions vs held-out test.

Shows what each occlusion type looks like at increasing budgets:
  Row 1: Fingerprint (trained on) — 3 budget levels
  Row 2: Glare (trained on) — 3 budget levels
  Row 3: Rain (never seen in training) — 3 budget levels

Each row cycles through low -> medium -> high budget to show the concept.
Rain frames are generated by applying the Rain model to clean frames.
"""

import subprocess
import sys
import tempfile
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "camera_occlusion"))

from PIL import Image, ImageDraw, ImageFont
from camera_occlusion.camera_noise import Rain, Glare

ROOT = Path(__file__).resolve().parent.parent
RESULTS = ROOT / "results"
OUT = ROOT / "docs" / "figures"


def get_font(size=15):
    for font_path in [
        "/System/Library/Fonts/Supplemental/Arial Bold.ttf",
        "/System/Library/Fonts/Supplemental/Helvetica Bold.ttf",
        "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf",
    ]:
        try:
            return ImageFont.truetype(font_path, size)
        except (OSError, IOError):
            continue
    return ImageFont.load_default()


def extract_frames(video_path, fps=4):
    """Extract frames from mp4 as list of numpy arrays (HWC uint8)."""
    with tempfile.TemporaryDirectory() as tmpdir:
        cmd = [
            "ffmpeg", "-y", "-i", str(video_path),
            "-vf", f"fps={fps}",
            f"{tmpdir}/frame_%04d.png",
        ]
        subprocess.run(cmd, capture_output=True, check=True)
        frames = []
        for p in sorted(Path(tmpdir).glob("frame_*.png")):
            frames.append(np.array(Image.open(p).convert("RGB")))
    return frames


def crop_and_resize(img_np, crop_top=30, size=(220, 176)):
    """Crop baked-in label from source videos, resize to panel size."""
    h, w = img_np.shape[:2]
    cropped = img_np[crop_top:h, :, :]
    return Image.fromarray(cropped).resize(size, Image.LANCZOS)


def add_bottom_label(img, text, color, font_size=12, bar_height=22):
    """Draw a colored label bar at the bottom of a PIL Image, in-place."""
    w, h = img.size
    draw = ImageDraw.Draw(img)
    font = get_font(font_size)
    y0 = h - bar_height
    draw.rectangle([(0, y0), (w, h)], fill=color)
    bbox = draw.textbbox((0, 0), text, font=font)
    tw = bbox[2] - bbox[0]
    draw.text(((w - tw) // 2, y0 + 4), text, fill="white", font=font)
    return img


def make_section_header(width, text, bg_color, height=24):
    """Create a section header strip."""
    header = Image.new("RGB", (width, height), bg_color)
    draw = ImageDraw.Draw(header)
    font = get_font(13)
    bbox = draw.textbbox((0, 0), text, font=font)
    tw = bbox[2] - bbox[0]
    draw.text(((width - tw) // 2, 4), text, fill="white", font=font)
    return header


def make_budget_label(width, text, height=18):
    """Small budget label strip."""
    strip = Image.new("RGB", (width, height), "#37474f")
    draw = ImageDraw.Draw(strip)
    font = get_font(11)
    bbox = draw.textbbox((0, 0), text, font=font)
    tw = bbox[2] - bbox[0]
    draw.text(((width - tw) // 2, 2), text, fill="#b0bec5", font=font)
    return strip


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    output = OUT / "simulation_demo.gif"

    pw, ph = 180, 144  # panel dimensions
    gap = 2

    # --- Extract clean and fingerprint/glare frames ---
    print("Extracting source frames...", flush=True)

    # Use the glare clean video since both clean videos are the same task
    clean_frames = extract_frames(
        RESULTS / "coke_can_glare" / "animations" / "clean.mp4", fps=3)
    fp90_frames = extract_frames(
        RESULTS / "coke_can_fingerprint" / "animations" /
        "worst_fingerprint_budget_0.90.mp4", fps=3)
    glare90_frames = extract_frames(
        RESULTS / "coke_can_glare" / "animations" /
        "worst_glare_budget_0.90.mp4", fps=3)

    n = min(len(clean_frames), len(fp90_frames), len(glare90_frames))
    print(f"  {n} frames available", flush=True)

    # --- Generate rain at 3 levels ---
    print("Generating rain frames...", flush=True)

    def apply_rain(frames, num_drops, radius_range):
        out = []
        for f in frames[:n]:
            rain = Rain(num_drops=num_drops, radius_range=radius_range)
            out.append(rain.apply(f.copy()))
        return out

    rain_lo = apply_rain(clean_frames, num_drops=40, radius_range=(3, 8))
    rain_mid = apply_rain(clean_frames, num_drops=200, radius_range=(5, 18))
    rain_hi = apply_rain(clean_frames, num_drops=500, radius_range=(8, 35))

    # --- Generate glare at lower budgets by blending ---
    # The glare90 frames are at max budget; create lighter versions
    # by blending with clean
    def blend_occlusion(clean_list, occluded_list, alpha):
        """Blend clean and occluded at alpha (0=clean, 1=full occlusion)."""
        out = []
        for c, o in zip(clean_list[:n], occluded_list[:n]):
            blended = (c.astype(np.float32) * (1 - alpha) +
                       o.astype(np.float32) * alpha)
            out.append(np.clip(blended, 0, 255).astype(np.uint8))
        return out

    glare_lo = blend_occlusion(clean_frames, glare90_frames, 0.3)
    glare_mid = blend_occlusion(clean_frames, glare90_frames, 0.6)

    # Similarly for fingerprint
    fp_lo = blend_occlusion(clean_frames, fp90_frames, 0.3)
    fp_mid = blend_occlusion(clean_frames, fp90_frames, 0.6)

    # --- Build animation ---
    # Layout: 3 columns (low / medium / high budget)
    #         3 rows (fingerprint / glare / rain)
    # With section headers

    print("Compositing frames...", flush=True)

    col_w = pw
    row_w = col_w * 3 + gap * 2
    budget_h = 18
    header_h = 24

    # Budget labels (static)
    bud_labels = [
        make_budget_label(col_w, "Budget: 10%"),
        make_budget_label(col_w, "Budget: 50%"),
        make_budget_label(col_w, "Budget: 90%"),
    ]

    # Section headers
    train_header = make_section_header(
        row_w, "TRAINED ON", "#2e7d32")
    test_header = make_section_header(
        row_w, "TESTED ON (never seen in training)", "#1565c0")

    # Row data: (section, label_text, frames_lo, frames_mid, frames_hi)
    rows = [
        ("train", "Fingerprint", fp_lo, fp_mid, fp90_frames),
        ("train", "Glare", glare_lo, glare_mid, glare90_frames),
        ("test",  "Rain", rain_lo, rain_mid, rain_hi),
    ]

    combined_frames = []
    for i in range(n):
        # Compute total height
        # train_header + budget_labels + fp_row + glare_row + gap +
        # test_header + budget_labels + rain_row
        total_h = (header_h + budget_h + ph +  # fingerprint
                   ph +                          # glare
                   3 +                            # gap
                   header_h + budget_h + ph)      # rain
        frame = Image.new("RGB", (row_w, total_h), "#263238")

        y = 0

        for row_idx, (section, label, lo, mid, hi) in enumerate(rows):
            # Section header (only before first row of each section)
            if row_idx == 0:
                frame.paste(train_header, (0, y))
                y += header_h
                # Budget labels
                for col, bl in enumerate(bud_labels):
                    frame.paste(bl, (col * (col_w + gap), y))
                y += budget_h
            elif row_idx == 2:
                y += 3  # gap between sections
                frame.paste(test_header, (0, y))
                y += header_h
                for col, bl in enumerate(bud_labels):
                    frame.paste(bl, (col * (col_w + gap), y))
                y += budget_h

            # Panels: low, mid, high
            for col, src in enumerate([lo, mid, hi]):
                panel = crop_and_resize(src[i], size=(pw, ph))
                add_bottom_label(panel, label,
                                 "#2e7d32" if section == "train" else "#1565c0",
                                 font_size=11)
                frame.paste(panel, (col * (col_w + gap), y))

            y += ph

        combined_frames.append(frame)

    # Save
    print("Saving GIF...", flush=True)
    quantized = [f.quantize(colors=96, method=Image.Quantize.MEDIANCUT)
                 for f in combined_frames]

    quantized[0].save(
        output,
        save_all=True,
        append_images=quantized[1:],
        duration=330,  # ~3 fps
        loop=0,
    )

    size_kb = output.stat().st_size / 1024
    print(f"  -> {output} ({size_kb:.0f} KB)", flush=True)


if __name__ == "__main__":
    main()
